/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "java_jbyteArray.h"
#include "bmp.h"
#ifndef WINDOWS
#include <wiringPi.h>
#include <wiringPiSPI.h>
#endif
/* Header for class top_zeimao77_terminal_nativec_OledSpi */

#ifndef _Included_top_zeimao77_terminal_nativec_OledSpi
#define _Included_top_zeimao77_terminal_nativec_OledSpi

#define OLED_RES 21
#define OLED_DC 22
#define OLED_CS 23

#ifdef __cplusplus
extern "C" {
#endif

void OLED_setFocus(unsigned char x, unsigned char y);
void OLED_gpioInit();
void OLED_writeCmd(unsigned char cmd);
void OLED_writeData(unsigned char data);
void OLED_clear(); 

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledInit
  (JNIEnv * env , jclass clazz);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledClear
  (JNIEnv * env , jclass clazz);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledDisplayOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledDisplayOn
  (JNIEnv * env , jclass clazz);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledDisplayOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledDisplayOff
  (JNIEnv * env, jclass clazz);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledDrawImg
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledDrawImg
  (JNIEnv * env, jclass clazz , jbyteArray byteArray);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledDrawChinese
 * Signature: (CC[B)V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledDrawChinese
  (JNIEnv * env, jclass clazz, jchar x0, jchar page, jbyteArray byteArray);

/*
 * Class:     top_zeimao77_terminal_nativec_OledSpi
 * Method:    oledDrawAscii
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_top_zeimao77_terminal_nativec_OledSpi_oledDrawAscii
  (JNIEnv * env, jclass clazz, jchar x0, jchar page , jchar ind);

#ifdef __cplusplus
}
#endif
#endif
