/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_zeimao77_terminal_nativec_Lm75aI2c */

#ifndef _Included_top_zeimao77_terminal_nativec_Lm75aI2c
#define _Included_top_zeimao77_terminal_nativec_Lm75aI2c

#ifndef WINDOWS
#include <wiringPi.h>
#include <wiringPiI2C.h>
#endif

#include <stdio.h>

#define LM75ADDR 0x48
int lm75a_fd = -1;
 

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_zeimao77_terminal_nativec_Lm75aI2c
 * Method:    lm75aInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_zeimao77_terminal_nativec_Lm75aI2c_lm75aInit
  (JNIEnv *env, jclass clazz);

/*
 * Class:     top_zeimao77_terminal_nativec_Lm75aI2c
 * Method:    lm75aGetTemp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_zeimao77_terminal_nativec_Lm75aI2c_lm75aGetTemp
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
