/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef WINDOWS
#include <wiringPi.h>
#endif
#include "common.h"
#include "java_jstring.h"
/* Header for class top_zeimao77_terminal_nativec_Gpion */

#ifndef _Included_top_zeimao77_terminal_nativec_Gpion
#define _Included_top_zeimao77_terminal_nativec_Gpion
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     top_zeimao77_terminal_nativec_Gpion
 * Method:    gpioInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_zeimao77_terminal_nativec_Gpion_gpioInit
  (JNIEnv * env, jclass clazz, jint index, jint mode);

/*
 * Class:     top_zeimao77_terminal_nativec_Gpion
 * Method:    gpioWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_zeimao77_terminal_nativec_Gpion_gpioWrite
  (JNIEnv * env, jclass clazz, jint index, jint value);

/*
 * Class:     top_zeimao77_terminal_nativec_Gpion
 * Method:    gpioRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_zeimao77_terminal_nativec_Gpion_gpioRead
  (JNIEnv * env, jclass clazz, jint index);


#ifdef __cplusplus
}
#endif
#endif
